// Reproducible compression; sharp is already supplied by Astro. Originals stay available.
import sharp from 'sharp';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
await mkdir('public/assets/optimized',{recursive:true});
const widths={ 'hero-roofing.png':[1280,1920], 'rooflume-logo.png':[250,500,750], 'about-roof-detail.jpg':[400,800,1200], 'about-roof-inspect.jpg':[400,800,1200], 'roofing-services.png':[400,800,1200], 'local-roofer.png':[400,800,1024], 'roofing-fleet.png':[640,1280] };
const manifest={};
for(const [file,sizes] of Object.entries(widths)){
 const name=file.replace(/\.[^.]+$/,''); const meta=await sharp('public/assets/'+file).metadata();manifest[file]={width:meta.width,height:meta.height,widths:sizes};
 for(const width of sizes)for(const format of ['avif','webp'])await sharp('public/assets/'+file).resize({width,withoutEnlargement:true}).toFormat(format,{quality:name==='rooflume-logo'?85:format==='avif'?65:82,effort:4}).toFile(`public/assets/optimized/${name}-${width}.${format}`);
}
await writeFile('src/assets/image-manifest.json',JSON.stringify(manifest,null,2));
// Keep the installed icon glyphs and metrics, but only ship selectors used by this page.
const page=await readFile('src/pages/index.astro','utf8');
const names=new Set([...page.matchAll(/ph-([a-z]+(?:-[a-z]+)*)/g)].map(m=>m[1]));
let css='/* Generated by qa/optimize-assets.mjs from the installed Phosphor package. */\n';
for(const weight of ['regular','fill']){
 const source=await readFile(`node_modules/@phosphor-icons/web/src/${weight}/style.css`,'utf8');
 const first=source.indexOf(weight==='fill'?'.ph-fill.ph-':'.ph.ph-');
 let base=source.slice(0,first).replace(/font-display: block/,'font-display: swap').replace(/src:[\s\S]*?;/,`src: url("/assets/optimized/Phosphor${weight==='fill'?'-Fill':''}.woff2") format("woff2");`);
 css+=base;
 for(const block of source.slice(first).matchAll(/([^{}]+)\{([^{}]+)\}/g))if([...names].some(n=>block[1].trim()===(weight==='fill'?'.ph-fill':'.ph')+'.ph-'+n+':before'))css+=block[0]+'\n';
}
await writeFile('src/styles/icons.css',css);
